global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'service-a'
    static_configs:
      - targets: ['servicea:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'service-b'
    static_configs:
      - targets: ['serviceb:5001']
    metrics_path: '/metrics'
    scrape_interval: 5s